const path = require('path');
const webpack = require('webpack');
const baseWebpackConfig = require('megadoc-html-serializer/webpack.config');

module.exports = function configureWebpack({
  runtimeConfigFilePath,
  runtimeStylesFilePath,
  runtimeOutputPath,
  tmpDir,
}) {
  return Object.assign({}, baseWebpackConfig, {
    devtool: false,

    entry: {
      'megadoc__config': [
        require.resolve('webpack-hot-middleware/client.js'),
        path.resolve(__dirname, '../ui/hotLoadConfig.js'),
        path.resolve(__dirname, '../ui/hotLoadStyles.js'),
      ],
    },

    module: {
      loaders: [
        {
          include: [ runtimeStylesFilePath ],
          loader: path.resolve(__dirname, '../webpack/md5-loader.js')
        }
      ]
    },

    output: {
      path: tmpDir,
      publicPath: runtimeOutputPath,
      pathinfo: false,
      filename: '[name].js',
      jsonpFunction: 'webpackJsonp_megadoc_html_live_server'
    },

    plugins: [
      new webpack.HotModuleReplacementPlugin(),
      new webpack.BannerPlugin('GENERATED BY MEGADOC-HTML-LIVE-SERVER', {
        entryOnly: true
      })
    ],

    resolve: {
      alias: {
        'megadoc-config-file$': runtimeConfigFilePath,
        'megadoc-styles-file$': runtimeStylesFilePath,
      },
    },
  });
}
