module.exports = {
  gitStats: false,
  id: 'articles',
  title: 'Articles',
  baseURL: null,
  source: [ 'doc/**/*.md' ],
  icon: null,
  exclude: [],
  fullFolderTitles: true,
  fullFolderTitleDelimiter: ' - ',
  allowLeadingSlashInLinks: true,
  generateMissingHeadings: true,
  discardIdPrefix: null,
  discardFileExtension: true,
};
