var fs = require('fs');
var path = require('path');
var marked = require('marked');
var _ = require('lodash');
var React = require('react');
var Utils = require('./Renderer/Utils');

var HeaderTmpl = _.template(
  fs.readFileSync(path.resolve(__dirname, 'Renderer', 'header.tmpl.html'), 'utf-8')
);

var RE_INTERNAL_LINK = Object.freeze(/^tiny:\/\//);
var RE_EXTERNAL_LINK = Object.freeze(/^https?:\/\//);

function createRenderer(config) {
  var renderer = new marked.Renderer();
  var markedOptions = Object.freeze({
    renderer: renderer,
    gfm: true,
    tables: true,
    sanitize: true,
    breaks: false,
    linkify: false,
    pedantic: false,
  });

  var state = { baseURL: '' };

  // this could be heavily optimized, but meh for now
  renderer.heading = function(text, level) {
    var id = (
      state.baseURL +
      '/' +
      Utils.normalizeHeading(Utils.sanitize(text.split('\n')[0]))
    );

    return HeaderTmpl({
      id: id,
      level: level,
      text: text,
      href: '#'+id
    });
  };

  renderer.link = function(href, title, text) {
    var props = {};

    props.href = href.replace(RE_INTERNAL_LINK, '');

    if (title) {
      props.title = title;
    }

    if (config.launchExternalLinksInNewTabs && href.match(RE_EXTERNAL_LINK)) {
      props.target = '_blank';
    }

    if (props.href !== href) {
      // When using History-based location, we need to mark internal links
      // generated by the LinkResolver with "data-internal" so that we can
      // intercept them and cause a transition when they're clicked, instead of
      // causing the browser to refresh.
      if (!config.useHashLocation) {
        props['data-internal'] = true;
      }
    }

    props.children = _.unescape(text);

    return React.renderToStaticMarkup(React.createElement('a', props))
  };

  return function renderMarkdown(text, options) {
    var html;

    options = options || {};
    state.baseURL = options.baseURL || '';

    html = marked(text, markedOptions);

    if (options && options.trimHTML) {
      html = Utils.trimHTML(html);
    }

    state.baseURL = '';

    return html;
  };
}

module.exports = createRenderer;