const Compiler = require('./Compiler');

exports.defaults = require('./config');
exports.run = Compiler.run;
exports.BREAKPOINT_COMPILE = Compiler.BREAKPOINT_COMPILE;
exports.BREAKPOINT_PARSE = Compiler.BREAKPOINT_PARSE;
exports.BREAKPOINT_REFINE = Compiler.BREAKPOINT_REFINE;
exports.BREAKPOINT_REDUCE = Compiler.BREAKPOINT_REDUCE;
exports.BREAKPOINT_RENDER = Compiler.BREAKPOINT_RENDER;
exports.BREAKPOINT_REDUCE_TREE = Compiler.BREAKPOINT_REDUCE_TREE;
exports.BREAKPOINT_COMPOSE_TREE = Compiler.BREAKPOINT_COMPOSE_TREE;
exports.BREAKPOINT_MERGE_CHANGE_TREE = Compiler.BREAKPOINT_MERGE_CHANGE_TREE;
exports.BREAKPOINT_RENDER_CORPUS = Compiler.BREAKPOINT_RENDER_CORPUS;
exports.BREAKPOINT_EMIT_ASSETS = Compiler.BREAKPOINT_EMIT_ASSETS;